# Generated by Django 4.2.2 on 2023-06-30 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name of Department')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Updated On')),
            ],
            options={
                'ordering': ['-updated_on'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Employee Name')),
                ('salary', models.PositiveIntegerField(blank=True, null=True, verbose_name='Salary')),
                ('joined_date', models.DateField(auto_now_add=True, null=True)),
                ('department_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department', to='core.department')),
            ],
            options={
                'ordering': ['-joined_date'],
            },
        ),
        migrations.AddField(
            model_name='department',
            name='employees',
            field=models.ManyToManyField(blank=True, null=True, to='core.employee', verbose_name='Employees'),
        ),
    ]
